// Auto-extracted card data for Lorcana 101 slides
// Source: ~/Project/claude/lorcana_card_db/json/setdata.*.json
window.LORCANA_CARDS = {
  "character_hero": {
    "id": 114,
    "fullName": "Maui - Hero to All",
    "name": "Maui",
    "version": "Hero to All",
    "type": "Character",
    "color": "Ruby",
    "cost": 5,
    "inkwell": true,
    "strength": 6,
    "willpower": 5,
    "lore": 0,
    "moveCost": null,
    "subtypesText": "Storyborn • Hero • Deity",
    "fullText": "Rush (This character can challenge the turn they're\nplayed.)\nReckless (This character can't quest and must\nchallenge each turn if able.)",
    "flavorText": "“What I believe you were trying to say is ‘Thank you.’”",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/114_baac7725205b3c3e4ab15794c678078c1a52afd8.jpg",
    "rarity": "Rare",
    "set": "1",
    "number": 114
  },
  "character_mickey": {
    "id": 115,
    "fullName": "Mickey Mouse - Brave Little Tailor",
    "name": "Mickey Mouse",
    "version": "Brave Little Tailor",
    "type": "Character",
    "color": "Ruby",
    "cost": 8,
    "inkwell": true,
    "strength": 5,
    "willpower": 5,
    "lore": 4,
    "moveCost": null,
    "subtypesText": "Dreamborn • Hero",
    "fullText": "Evasive (Only characters with Evasive can\nchallenge this character.)",
    "flavorText": "When defeat looms and victory hangs by a thread,\na hero bolts to the rescue, patching things up\nthrough shear determination.",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/115_f65680bc6fbc8461a090d81a4e60f3080aa2bca8.jpg",
    "rarity": "Legendary",
    "set": "1",
    "number": 115
  },
  "character_elsa": {
    "id": 41,
    "fullName": "Elsa - Snow Queen",
    "name": "Elsa",
    "version": "Snow Queen",
    "type": "Character",
    "color": "Amethyst",
    "cost": 3,
    "inkwell": true,
    "strength": 2,
    "willpower": 3,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Dreamborn • Hero • Queen • Sorcerer",
    "fullText": "FREEZE ⟳ — Exert chosen opposing character.",
    "flavorText": "Recreated by magical ink, Elsa found herself in\nan entirely new world. Fortunately, ice works the\nsame way everywhere.",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/41_23da670a1d0bf54139cdea9af6f33f1bad868970.jpg",
    "rarity": "Uncommon",
    "set": "1",
    "number": 41
  },
  "character_stitch": {
    "id": 21,
    "fullName": "Stitch - Carefree Surfer",
    "name": "Stitch",
    "version": "Carefree Surfer",
    "type": "Character",
    "color": "Amber",
    "cost": 7,
    "inkwell": true,
    "strength": 4,
    "willpower": 8,
    "lore": 2,
    "moveCost": null,
    "subtypesText": "Dreamborn • Hero • Alien",
    "fullText": "OHANA When you play this character, if you have 2 or\nmore other characters in play, you may draw 2 cards.",
    "flavorText": "“So you're from outer space, huh? I hear the surfing's\nchoice.”\n—David",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/21_c9313d800707f408e740502a15578f53314c125a.jpg",
    "rarity": "Legendary",
    "set": "1",
    "number": 21
  },
  "item_dingle": {
    "id": 32,
    "fullName": "Dinglehopper",
    "name": "Dinglehopper",
    "version": "",
    "type": "Item",
    "color": "Amber",
    "cost": 1,
    "inkwell": true,
    "strength": null,
    "willpower": null,
    "lore": null,
    "moveCost": null,
    "subtypesText": "",
    "fullText": "STRAIGHTEN HAIR ⟳ — Remove up to 1 damage\nfrom chosen character.",
    "flavorText": "Enjoy the finest of human hairstyles!",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/32_36afc47a05bb4a3dace4531c1db24cce7fcbceb7.jpg",
    "rarity": "Common",
    "set": "1",
    "number": 32
  },
  "item_flower": {
    "id": 169,
    "fullName": "Magic Golden Flower",
    "name": "Magic Golden Flower",
    "version": "",
    "type": "Item",
    "color": "Sapphire",
    "cost": 1,
    "inkwell": true,
    "strength": null,
    "willpower": null,
    "lore": null,
    "moveCost": null,
    "subtypesText": "",
    "fullText": "HEALING POLLEN Banish this item — Remove up to 3\ndamage from chosen character.",
    "flavorText": "“Once upon a time, a single drop of sunlight fell from\nthe heavens....”\n—Flynn Rider",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/169_f111efa255693402d45ed0a8c73a807daddfb894.jpg",
    "rarity": "Common",
    "set": "1",
    "number": 169
  },
  "action_dragonfire": {
    "id": 130,
    "fullName": "Dragon Fire",
    "name": "Dragon Fire",
    "version": "",
    "type": "Action",
    "color": "Ruby",
    "cost": 5,
    "inkwell": false,
    "strength": null,
    "willpower": null,
    "lore": null,
    "moveCost": null,
    "subtypesText": "",
    "fullText": "Banish chosen character.",
    "flavorText": "Rare is the hero who can withstand a dragon's wrath.",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/130_decfce2e256561e57abe8d2d5e378a3781c2ee6d.jpg",
    "rarity": "Uncommon",
    "set": "1",
    "number": 130
  },
  "song_friends": {
    "id": 64,
    "fullName": "Friends on the Other Side",
    "name": "Friends on the Other Side",
    "version": "",
    "type": "Action",
    "color": "Amethyst",
    "cost": 3,
    "inkwell": true,
    "strength": null,
    "willpower": null,
    "lore": null,
    "moveCost": null,
    "subtypesText": "Song",
    "fullText": "(A character with cost 3 or more can ⟳ to sing this song\nfor free.)\nDraw 2 cards.",
    "flavorText": "The cards, the cards\nthe cards will tell...",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/64_1514c2d3747bf9fd1229fe4a2db08042949ed967.jpg",
    "rarity": "Common",
    "set": "1",
    "number": 64
  },
  "song_beourguest": {
    "id": 25,
    "fullName": "Be Our Guest",
    "name": "Be Our Guest",
    "version": "",
    "type": "Action",
    "color": "Amber",
    "cost": 2,
    "inkwell": true,
    "strength": null,
    "willpower": null,
    "lore": null,
    "moveCost": null,
    "subtypesText": "Song",
    "fullText": "(A character with cost 2 or more can ⟳ to sing this\nsong for free.)\nLook at the top 4 cards of your deck. You may reveal a\ncharacter card and put it into your hand. Put the rest\non the bottom of your deck in any order.",
    "flavorText": "",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/25_70ed49868782fed4a347083366d534f041af88a6.jpg",
    "rarity": "Uncommon",
    "set": "1",
    "number": 25
  },
  "song_grabsword": {
    "id": 198,
    "fullName": "Grab Your Sword",
    "name": "Grab Your Sword",
    "version": "",
    "type": "Action",
    "color": "Steel",
    "cost": 5,
    "inkwell": false,
    "strength": null,
    "willpower": null,
    "lore": null,
    "moveCost": null,
    "subtypesText": "Song",
    "fullText": "(A character with cost 5 or more can ⟳ to sing this song for\nfree.)\nDeal 2 damage to each opposing character.",
    "flavorText": "We don't like\nWhat we don't understand\nIn fact, it scares us",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/198_5a48b0a8d038167dc3e152c2ead53a3def28d18c.jpg",
    "rarity": "Rare",
    "set": "1",
    "number": 198
  },
  "location_illuminary": {
    "id": 2257,
    "fullName": "The Great Illuminary - Abandoned Laboratory",
    "name": "The Great Illuminary",
    "version": "Abandoned Laboratory",
    "type": "Location",
    "color": "Amethyst",
    "cost": 2,
    "inkwell": true,
    "strength": null,
    "willpower": 3,
    "lore": 1,
    "moveCost": 1,
    "subtypesText": "",
    "fullText": "STARTLING DISCOVERY Characters gain “⟳ — Draw a card” while here.",
    "flavorText": "“Remember, we're looking for clues to who tore up the lorebook pages.”\n—Elisa Maza",
    "image": "https://api.lorcana.ravensburger.com/images/en/set10/68_a50f12321fcf05a2d15ea5f8e37e8715083a3d65.jpg",
    "rarity": "Uncommon",
    "set": "10",
    "number": 68
  },
  "challenge_horseman": {
    "id": 2314,
    "fullName": "The Headless Horseman - Terror of Sleepy Hollow",
    "name": "The Headless Horseman",
    "version": "Terror of Sleepy Hollow",
    "type": "Character",
    "color": "Ruby",
    "cost": 5,
    "inkwell": false,
    "strength": 4,
    "willpower": 2,
    "lore": 2,
    "moveCost": null,
    "subtypesText": "Storyborn • Villain",
    "fullText": "LEAVES NO TRACE When you play this character,\nbanish chosen opposing character with 2 ¤ or less.\nGATHERING STRENGTH During your turn, whenever\nan opposing character is banished, each of your\ncharacters gets +1 ¤ this turn.",
    "flavorText": "",
    "image": "https://api.lorcana.ravensburger.com/images/en/set10/125_9972a2635cc3e30a59272aabab81b5f17aa25ee2.jpg",
    "rarity": "Legendary",
    "set": "10",
    "number": 125
  },
  "challenge_rapunzel": {
    "id": 2332,
    "fullName": "Rapunzel - Creative Captor",
    "name": "Rapunzel",
    "version": "Creative Captor",
    "type": "Character",
    "color": "Sapphire",
    "cost": 5,
    "inkwell": true,
    "strength": 3,
    "willpower": 6,
    "lore": 2,
    "moveCost": null,
    "subtypesText": "Storyborn • Hero • Princess",
    "fullText": "ENSNARL When you play this character, chosen\nopposing character gets -3 ¤ this turn.",
    "flavorText": "“Well, that should slow you down for a minute.”",
    "image": "https://api.lorcana.ravensburger.com/images/en/set10/143_8fbd751d486ce62a073001642823f80dbe6fcbd6.jpg",
    "rarity": "Common",
    "set": "10",
    "number": 143
  },
  "kw_rush": {
    "id": 43,
    "fullName": "Flotsam - Ursula's Spy",
    "name": "Flotsam",
    "version": "Ursula's Spy",
    "type": "Character",
    "color": "Amethyst",
    "cost": 5,
    "inkwell": false,
    "strength": 3,
    "willpower": 4,
    "lore": 2,
    "moveCost": null,
    "subtypesText": "Storyborn • Ally",
    "fullText": "Rush (This character can challenge the turn they're\nplayed.)\nDEXTEROUS LUNGE Your characters named\nJetsam gain Rush.",
    "flavorText": "“We know someone who can help you...for a price.”",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/43_8d497710d66bfb4778e4c66043107d87b7174394.jpg",
    "rarity": "Rare",
    "set": "1",
    "number": 43
  },
  "kw_evasive": {
    "id": 46,
    "fullName": "Jetsam - Ursula's Spy",
    "name": "Jetsam",
    "version": "Ursula's Spy",
    "type": "Character",
    "color": "Amethyst",
    "cost": 4,
    "inkwell": true,
    "strength": 3,
    "willpower": 3,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Ally",
    "fullText": "Evasive (Only characters with Evasive can\nchallenge this character.)\nSINISTER SLITHER Your characters named\nFlotsam gain Evasive.",
    "flavorText": "“We can help you get anything you want....”",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/46_01f1336c2d69344ac9d004d2a20d7b02e88f3ddb.jpg",
    "rarity": "Common",
    "set": "1",
    "number": 46
  },
  "kw_ward": {
    "id": 69,
    "fullName": "Aladdin - Prince Ali",
    "name": "Aladdin",
    "version": "Prince Ali",
    "type": "Character",
    "color": "Emerald",
    "cost": 2,
    "inkwell": true,
    "strength": 2,
    "willpower": 2,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Hero • Prince",
    "fullText": "Ward (Opponents can't choose this character\nexcept to challenge.)",
    "flavorText": "Fabulously wealthy. Practically untouchable.\nGenuinely inauthentic.",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/69_567caacf82f67ff08587b6ded1c7ebeb1f77a196.jpg",
    "rarity": "Common",
    "set": "1",
    "number": 69
  },
  "kw_bodyguard": {
    "id": 4,
    "fullName": "Goofy - Musketeer",
    "name": "Goofy",
    "version": "Musketeer",
    "type": "Character",
    "color": "Amber",
    "cost": 5,
    "inkwell": true,
    "strength": 3,
    "willpower": 6,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Dreamborn • Hero • Musketeer",
    "fullText": "Bodyguard (This character may enter play exerted. An\nopposing character who challenges one of your characters\nmust choose one with Bodyguard if able.)\nAND TWO FOR TEA! When you play this character, you\nmay remove up to 2 damage from each of your Musketeer\ncharacters.",
    "flavorText": "“En gawrsh!”",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/4_add38edeb287c4de4be302549b684e41b54f1519.jpg",
    "rarity": "Uncommon",
    "set": "1",
    "number": 4
  },
  "kw_support": {
    "id": 7,
    "fullName": "HeiHei - Boat Snack",
    "name": "HeiHei",
    "version": "Boat Snack",
    "type": "Character",
    "color": "Amber",
    "cost": 1,
    "inkwell": true,
    "strength": 1,
    "willpower": 2,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Ally",
    "fullText": "Support (Whenever this character quests, you\nmay add their ¤ to another chosen character's\n¤ this turn.)",
    "flavorText": "“Sometimes, our strengths lie beneath the surface.\nFar beneath, in some cases....”\n—Moana",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/7_ba58282d94d84de5e8d6675845a1a17f90f104c0.jpg",
    "rarity": "Common",
    "set": "1",
    "number": 7
  },
  "kw_reckless": {
    "id": 80,
    "fullName": "Iago - Loud-Mouthed Parrot",
    "name": "Iago",
    "version": "Loud-Mouthed Parrot",
    "type": "Character",
    "color": "Emerald",
    "cost": 3,
    "inkwell": true,
    "strength": 1,
    "willpower": 4,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Ally",
    "fullText": "YOU GOT A PROBLEM? ⟳ — Chosen character\ngains Reckless during their next turn. (They can't\nquest and must challenge if able.)",
    "flavorText": "",
    "image": "https://api.lorcana.ravensburger.com/images/en/set1/80_43fa1f57b139165f51d0728db6fb6f708f7b41ef.jpg",
    "rarity": "Rare",
    "set": "1",
    "number": 80
  },
  "sim_robin_beloved": {
    "id": 625,
    "fullName": "Robin Hood - Beloved Outlaw",
    "name": "Robin Hood",
    "version": "Beloved Outlaw",
    "type": "Character",
    "color": "Steel",
    "cost": 1,
    "inkwell": true,
    "strength": 2,
    "willpower": 2,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Hero",
    "fullText": "",
    "flavorText": "“You call this an ambush? Tsk, tsk. It's barely a\nbushwhack.”",
    "image": "https://api.lorcana.ravensburger.com/images/en/set3/189_05b50f56b53ceec9a7a5983d5f819cef6a7d61f6.jpg",
    "rarity": "Common",
    "set": "3",
    "number": 189
  },
  "sim_mulan": {
    "id": 2449,
    "fullName": "Mulan - Disguised Soldier",
    "name": "Mulan",
    "version": "Disguised Soldier",
    "type": "Character",
    "color": "Steel",
    "cost": 1,
    "inkwell": true,
    "strength": 2,
    "willpower": 1,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Hero • Princess",
    "fullText": "WHERE DO I SIGN IN? When you play this\ncharacter, you may draw a card, then choose and\ndiscard a card.",
    "flavorText": "“Okay this is it, time to show 'em your man walk.”\n—Mushu",
    "image": "https://api.lorcana.ravensburger.com/images/en/promo3/38_6ecb0f1c83f2a12d7fbdc578b31fff2883a734e6.jpg",
    "rarity": "Special",
    "set": "7",
    "number": 38
  },
  "sim_robin_champion": {
    "id": 2113,
    "fullName": "Robin Hood - Champion of Sherwood",
    "name": "Robin Hood",
    "version": "Champion of Sherwood",
    "type": "Character",
    "color": "Steel",
    "cost": 5,
    "inkwell": true,
    "strength": 3,
    "willpower": 6,
    "lore": 2,
    "moveCost": null,
    "subtypesText": "Floodborn • Hero",
    "fullText": "Shift 3 ⬡ (You may pay 3 ⬡ to play this on top of one of your\ncharacters named Robin Hood.)\nSKILLED COMBATANT During your turn, whenever this\ncharacter banishes another character in a challenge, gain 2 lore.\nTHE GOOD OF OTHERS When this character is banished in a\nchallenge, you may draw a card.",
    "flavorText": "",
    "image": "https://api.lorcana.ravensburger.com/images/en/set9/177_e5101df6eaee76e77b9fd747346b771cde79d5cd.jpg",
    "rarity": "Legendary",
    "set": "9",
    "number": 177
  },
  "sim_pluto": {
    "id": 1957,
    "fullName": "Pluto - Friendly Pooch",
    "name": "Pluto",
    "version": "Friendly Pooch",
    "type": "Character",
    "color": "Amber",
    "cost": 1,
    "inkwell": false,
    "strength": 0,
    "willpower": 2,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Ally",
    "fullText": "GOOD DOG ⟳ — You pay 1 ⬡ less for the next\ncharacter you play this turn.",
    "flavorText": "He just can't wait for new friends to arrive!",
    "image": "https://api.lorcana.ravensburger.com/images/en/set9/21_f98621a3fcd7c434a0db994dd295b0f74ac93d9d.jpg",
    "rarity": "Common",
    "set": "9",
    "number": 21
  },
  "sim_rajah": {
    "id": 2195,
    "fullName": "Rajah - Devoted Protector",
    "name": "Rajah",
    "version": "Devoted Protector",
    "type": "Character",
    "color": "Amber",
    "cost": 3,
    "inkwell": true,
    "strength": 3,
    "willpower": 4,
    "lore": 1,
    "moveCost": null,
    "subtypesText": "Storyborn • Ally",
    "fullText": "Bodyguard (This character may enter play exerted.\nAn opposing character who challenges one of\nyour characters must choose one with Bodyguard\nif able.)",
    "flavorText": "He's determined to protect his friends, no matter\nwhat forms they take.",
    "image": "https://api.lorcana.ravensburger.com/images/en/set10/6_f3e8cbaf1f7d32acf45b5f025bf61918087bfd3f.jpg",
    "rarity": "Common",
    "set": "10",
    "number": 6
  },
  "song_newworld": {"abilities":[{"effect":"A character with cost 5 or more can ⟳ to sing this song for free.","fullText":"(A character with cost 5 or more can ⟳ to sing this\nsong for free.)","type":"static"}],"allowedInFormats":{"Core":{"allowed":false,"allowedUntilDate":"2025-09-05"},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2023-09-08","artists":["Koni"],"artistsText":"Koni","clarifications":["Q: What happens if someone plays A Whole New World when all players have fewer than 7 cards left in their deck?\nA: The active player resolves first, so that player would lose the game."],"code":"39","color":"Steel","cost":5,"effects":["Each player discards their hand and draws 7 cards."],"externalLinks":{"cardTraderId":258918,"cardTraderUrl":"https://www.cardtrader.com/cards/258918","cardmarketId":729383,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/The-First-Chapter/A-Whole-New-World?language=1","tcgPlayerId":506088,"tcgPlayerUrl":"https://www.tcgplayer.com/product/506088"},"flavorText":"Shining, shimmering, splendid...","foilTypes":["None","Silver"],"fullIdentifier":"195/204 • EN • 1","fullName":"A Whole New World","fullText":"(A character with cost 5 or more can ⟳ to sing this\nsong for free.)\nEach player discards their hand and draws 7 cards.","fullTextSections":["(A character with cost 5 or more can ⟳ to sing this\nsong for free.)","Each player discards their hand and draws 7 cards."],"id":195,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set1/195_21059cf99a1b8c633100201b7c7ff090868258eb.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set1/195_94542b1a94127cea3923cf9975650520a9a08151.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set1/195_18333bc1be91df24f64e34b540bde8d66e6ef992.jpg"},"inkwell":false,"name":"A Whole New World","number":195,"promoIds":[1199],"rarity":"Super Rare","simpleName":"a whole new world","story":"Aladdin","subtypes":["Song"],"subtypesText":"Song","type":"Action","image":"https://api.lorcana.ravensburger.com/images/en/set1/195_94542b1a94127cea3923cf9975650520a9a08151.jpg"},
  "song_letitgo": {"abilities":[{"effect":"A character with cost 5 or more can ⟳ to sing this song for free.","fullText":"(A character with cost 5 or more can ⟳ to sing this song for free.)","type":"static"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2023-09-08","artists":["Milica Celikovic"],"artistsText":"Milica Celikovic","code":"2D","color":"Sapphire","cost":5,"effects":["Put chosen character into their player's inkwell facedown and\nexerted."],"externalLinks":{"cardTraderId":259385,"cardTraderUrl":"https://www.cardtrader.com/cards/259385","cardmarketId":729351,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/The-First-Chapter/Let-It-Go?language=1","tcgPlayerId":492997,"tcgPlayerUrl":"https://www.tcgplayer.com/product/492997"},"flavorText":"It's time to see what I can do\nTo test the limits and break through","foilTypes":["None","Silver"],"fullIdentifier":"163/204 • EN • 1","fullName":"Let It Go","fullText":"(A character with cost 5 or more can ⟳ to sing this song for free.)\nPut chosen character into their player's inkwell facedown and\nexerted.","fullTextSections":["(A character with cost 5 or more can ⟳ to sing this song for free.)","Put chosen character into their player's inkwell facedown and\nexerted."],"id":163,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set1/163_0d183f7e37b9293a5f54570f41780a591872f387.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set1/163_4f979476a1bf4097c7e9020bea78fa7fd8712a4e.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set1/163_07231a42c00c49d1323138d07da90f61f3d4a438.jpg"},"inkwell":true,"name":"Let It Go","number":163,"promoIds":[1188],"rarity":"Rare","reprintedAsIds":[2626],"simpleName":"let it go","story":"Frozen","subtypes":["Song"],"subtypesText":"Song","type":"Action","image":"https://api.lorcana.ravensburger.com/images/en/set1/163_4f979476a1bf4097c7e9020bea78fa7fd8712a4e.jpg"},
  "song_spooky": {"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2025-11-07","artists":["Mariana Moreno"],"artistsText":"Mariana Moreno","code":"BY","color":"Sapphire","cost":6,"effects":["Put all characters with cost 3 or less into their players'\ninkwells facedown and exerted."],"enchantedId":2426,"externalLinks":{"cardTraderId":356592,"cardTraderUrl":"https://www.cardtrader.com/cards/356592","cardmarketId":856188,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/Whispers-in-the-Well/Spooky-Sight-V1?language=1","tcgPlayerId":660005,"tcgPlayerUrl":"https://www.tcgplayer.com/product/660005"},"flavorText":"“We've got to get out of here!”\n—Mickey Mouse","foilTypes":["None","Silver"],"fullIdentifier":"165/204 • EN • 10","fullName":"Spooky Sight","fullText":"Put all characters with cost 3 or less into their players'\ninkwells facedown and exerted.","fullTextSections":["Put all characters with cost 3 or less into their players'\ninkwells facedown and exerted."],"id":2354,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set10/165_f5e52746080957c4a8cd37b7117241d3c2d060c7.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set10/165_850002a114cf26e39a381404685658c8dd594299.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set10/165_6f67b0c1e2ce1e16fac5968ef8f600781926631b.jpg"},"inkwell":false,"name":"Spooky Sight","number":165,"rarity":"Rare","simpleName":"spooky sight","story":"Mickey Mouse & Friends","type":"Action","image":"https://api.lorcana.ravensburger.com/images/en/set10/165_850002a114cf26e39a381404685658c8dd594299.jpg"},
  "character_cinderella_dream": {"abilities":[{"effect":"At the end of your turn, if you played a Princess character this turn, you may put a card from your hand into your inkwell facedown to draw a card.","fullText":"WHATEVER YOU WISH FOR At the end of your turn,\nif you played a Princess character this turn, you\nmay put a card from your hand into your inkwell\nfacedown to draw a card.","name":"WHATEVER YOU WISH FOR","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2025-11-07","artists":["Brittney Hackett"],"artistsText":"Brittney Hackett","code":"BO","color":"Sapphire","cost":4,"enchantedId":2425,"externalLinks":{"cardTraderId":356584,"cardTraderUrl":"https://www.cardtrader.com/cards/356584","cardmarketId":856178,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/Whispers-in-the-Well/Cinderella-Dream-Come-True-V1?language=1","tcgPlayerId":658344,"tcgPlayerUrl":"https://www.tcgplayer.com/product/658344"},"foilTypes":["None","Silver"],"fullIdentifier":"155/204 • EN • 10","fullName":"Cinderella - Dream Come True","fullText":"WHATEVER YOU WISH FOR At the end of your turn,\nif you played a Princess character this turn, you\nmay put a card from your hand into your inkwell\nfacedown to draw a card.","fullTextSections":["WHATEVER YOU WISH FOR At the end of your turn,\nif you played a Princess character this turn, you\nmay put a card from your hand into your inkwell\nfacedown to draw a card."],"id":2344,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set10/155_ff1810915f9e4fd2e7770d89ec313ddc349c7774.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set10/155_a0de4c4761627b712b187a85945066668e2cd982.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set10/155_878f2ca9c3008df27f40209650cc21d3cd2ed0a4.jpg","varnishMask":"https://api.lorcana.ravensburger.com/images/en/set10/155_51e96736f39332e24bbeed088e0ace57e91b674c.jpg"},"inkwell":false,"lore":1,"name":"Cinderella","number":155,"rarity":"Legendary","simpleName":"cinderella dream come true","story":"Cinderella","strength":2,"subtypes":["Storyborn","Hero","Princess"],"subtypesText":"Storyborn • Hero • Princess","type":"Character","varnishType":"HighGloss","version":"Dream Come True","willpower":3,"image":"https://api.lorcana.ravensburger.com/images/en/set10/155_a0de4c4761627b712b187a85945066668e2cd982.jpg"},
  "character_merida_archer": {"abilities":[{"effect":"When you play this character, you may return an action card named Three Arrows from your discard to your hand.","fullText":"FULL QUIVER When you play this character, you\nmay return an action card named Three Arrows\nfrom your discard to your hand.","name":"FULL QUIVER","type":"triggered"},{"effect":"Whenever one of your actions deals damage to an opposing character, deal 2 damage to that character.","fullText":"STEADY AIM Whenever one of your actions deals\ndamage to an opposing character, deal 2 damage\nto that character.","name":"STEADY AIM","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2026-05-08","artists":["Max Ulichney"],"artistsText":"Max Ulichney","code":"KS","color":"Steel","cost":5,"externalLinks":{},"foilTypes":["None","Silver"],"fullIdentifier":"191/204 • EN • 12","fullName":"Merida - Formidable Archer","fullText":"FULL QUIVER When you play this character, you\nmay return an action card named Three Arrows\nfrom your discard to your hand.\nSTEADY AIM Whenever one of your actions deals\ndamage to an opposing character, deal 2 damage\nto that character.","fullTextSections":["FULL QUIVER When you play this character, you\nmay return an action card named Three Arrows\nfrom your discard to your hand.","STEADY AIM Whenever one of your actions deals\ndamage to an opposing character, deal 2 damage\nto that character."],"iconicId":2957,"id":2906,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set12/191_f361b569e1a97ce2ddbc3030f15e154c72e86339.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set12/191_b2f9a5146af6e1e9f706b8a9ed842335f93d938b.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set12/191_214f8455c3650db55cea45640a0068c1837740cd.jpg","varnishMask":"https://api.lorcana.ravensburger.com/images/en/set12/191_93124383117d9dda9a0b7b5c29050f1e6f4311fa.jpg"},"inkwell":false,"lore":2,"name":"Merida","number":191,"rarity":"Legendary","simpleName":"merida formidable archer","story":"Brave","strength":3,"subtypes":["Storyborn","Hero","Princess"],"subtypesText":"Storyborn • Hero • Princess","type":"Character","varnishType":"HighGloss","version":"Formidable Archer","willpower":5,"image":"https://api.lorcana.ravensburger.com/images/en/set12/191_b2f9a5146af6e1e9f706b8a9ed842335f93d938b.jpg"},
  "character_pete_ghost": {"abilities":[{"fullText":"Boost 1 ⬡ (Once during your turn, you may pay 1 ⬡ to put\nthe top card of your deck facedown under this character.)","keyword":"Boost","keywordValue":"1","keywordValueNumber":1,"reminderText":"Once during your turn, you may pay 1 ⬡ to put the top card of your deck facedown under this character.","type":"keyword"},{"effect":"Whenever this character quests, look at a number of cards from the top of your deck equal to the number of cards under him. Put one into your hand and put the rest on the bottom of your deck in any order.","fullText":"FOREBODING GLANCE Whenever this character quests, look\nat a number of cards from the top of your deck equal to the\nnumber of cards under him. Put one into your hand and put\nthe rest on the bottom of your deck in any order.","name":"FOREBODING GLANCE","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2026-02-13","artists":["Valerio Buonfantino"],"artistsText":"Valerio Buonfantino","code":"Gd","color":"Sapphire","cost":5,"externalLinks":{},"foilTypes":["None","Silver"],"fullIdentifier":"154/204 • EN • 11","fullName":"Pete - Ghost of Christmas Future","fullText":"Boost 1 ⬡ (Once during your turn, you may pay 1 ⬡ to put\nthe top card of your deck facedown under this character.)\nFOREBODING GLANCE Whenever this character quests, look\nat a number of cards from the top of your deck equal to the\nnumber of cards under him. Put one into your hand and put\nthe rest on the bottom of your deck in any order.","fullTextSections":["Boost 1 ⬡ (Once during your turn, you may pay 1 ⬡ to put\nthe top card of your deck facedown under this character.)","FOREBODING GLANCE Whenever this character quests, look\nat a number of cards from the top of your deck equal to the\nnumber of cards under him. Put one into your hand and put\nthe rest on the bottom of your deck in any order."],"id":2617,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set11/154_99cf4a02dacd4aed07f96b48e933fae5b7f7f0be.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set11/154_06745b50b5a9fc4bb5f4f87e814af9ff0dfbb44b.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set11/154_b8ce2f362614b415d9a109c690b58c0444f3be16.jpg"},"inkwell":true,"keywordAbilities":["Boost"],"lore":1,"name":"Pete","number":154,"rarity":"Rare","simpleName":"pete ghost of christmas future","story":"Mickey's Christmas Carol","strength":5,"subtypes":["Storyborn","Ally","Ghost"],"subtypesText":"Storyborn • Ally • Ghost","type":"Character","version":"Ghost of Christmas Future","willpower":5,"image":"https://api.lorcana.ravensburger.com/images/en/set11/154_06745b50b5a9fc4bb5f4f87e814af9ff0dfbb44b.jpg"},
  "character_moana_curious": {"abilities":[{"effect":"You can ink cards from your discard.","fullText":"ANCESTRAL LEGACY You can ink cards from\nyour discard.","name":"ANCESTRAL LEGACY","type":"static"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2026-02-13","artists":["Rizal Badar"],"artistsText":"Rizal Badar","code":"Ge","color":"Sapphire","cost":5,"externalLinks":{},"flavorText":"“I've never seen anything like this before! It's so\ndazzling, so beautiful. So...cold.”","foilTypes":["None","Silver"],"fullIdentifier":"155/204 • EN • 11","fullName":"Moana - Curious Explorer","fullText":"ANCESTRAL LEGACY You can ink cards from\nyour discard.","fullTextSections":["ANCESTRAL LEGACY You can ink cards from\nyour discard."],"iconicId":2705,"id":2618,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set11/155_a58e75fb9fefaca86652ce43dff3f125d4232f48.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set11/155_02c48a20c00faeccae34b1d0cee3e82fcfd1b5ba.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set11/155_f989124b39917c67fc1744c69264eee4664c42c3.jpg","varnishMask":"https://api.lorcana.ravensburger.com/images/en/set11/155_0bbbedfefd5b6f853f1a8f9d9dfa0d3cd1337c5b.jpg"},"inkwell":true,"lore":2,"name":"Moana","number":155,"rarity":"Legendary","simpleName":"moana curious explorer","story":"Moana","strength":4,"subtypes":["Storyborn","Hero","Princess"],"subtypesText":"Storyborn • Hero • Princess","type":"Character","varnishType":"HighGloss","version":"Curious Explorer","willpower":4,"image":"https://api.lorcana.ravensburger.com/images/en/set11/155_02c48a20c00faeccae34b1d0cee3e82fcfd1b5ba.jpg"},
  "character_aurora_dream": {"abilities":[{"fullText":"Shift 3 (You may pay 3 ⬡ to play this on top of one of\nyour characters named Aurora.)","keyword":"Shift","keywordValue":"3","keywordValueNumber":3,"reminderText":"You may pay 3 ⬡ to play this on top of one of your characters named Aurora.","type":"keyword"},{"effect":"Your other characters gain Ward. (Opponents can't choose them except to challenge.)","fullText":"PROTECTIVE EMBRACE Your other characters\ngain Ward. (Opponents can't choose them except to\nchallenge.)","name":"PROTECTIVE EMBRACE","type":"static"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2023-09-08","artists":["Nicholas Kole"],"artistsText":"Nicholas Kole","code":"2f","color":"Sapphire","cost":5,"enchantedId":213,"externalLinks":{"cardTraderId":258921,"cardTraderUrl":"https://www.cardtrader.com/cards/258921","cardmarketId":729327,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/The-First-Chapter/Aurora-Dreaming-Guardian-V1?language=1","tcgPlayerId":493497,"tcgPlayerUrl":"https://www.tcgplayer.com/product/493497"},"flavorText":"As the princess slumbered, her power awoke.","foilTypes":["None","Silver"],"fullIdentifier":"139/204 • EN • 1","fullName":"Aurora - Dreaming Guardian","fullText":"Shift 3 (You may pay 3 ⬡ to play this on top of one of\nyour characters named Aurora.)\nPROTECTIVE EMBRACE Your other characters\ngain Ward. (Opponents can't choose them except to\nchallenge.)","fullTextSections":["Shift 3 (You may pay 3 ⬡ to play this on top of one of\nyour characters named Aurora.)","PROTECTIVE EMBRACE Your other characters\ngain Ward. (Opponents can't choose them except to\nchallenge.)"],"id":139,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set1/139_bf399e594e0377974bd4848483f20b2ce4844835.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set1/139_4e37ba93dd8d0282dbad80c4441f042729f1c817.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set1/139_dfe20228b5a2df4adbb372abcd196f9aa4567851.jpg"},"inkwell":true,"keywordAbilities":["Shift"],"lore":2,"name":"Aurora","number":139,"rarity":"Super Rare","reprintedAsIds":[2089],"simpleName":"aurora dreaming guardian","story":"Sleeping Beauty","strength":3,"subtypes":["Floodborn","Hero","Princess"],"subtypesText":"Floodborn • Hero • Princess","type":"Character","version":"Dreaming Guardian","willpower":5,"image":"https://api.lorcana.ravensburger.com/images/en/set1/139_4e37ba93dd8d0282dbad80c4441f042729f1c817.jpg"},
  "character_vanellope_sugar": {"abilities":[{"fullText":"Shift 2 (You may pay 2 ⬡ to play this on top of one of\nyour characters named Vanellope von Schweetz.)","keyword":"Shift","keywordValue":"2","keywordValueNumber":2,"reminderText":"You may pay 2 ⬡ to play this on top of one of your characters named Vanellope von Schweetz.","type":"keyword"},{"effect":"Whenever you play another Princess character, all opposing characters get -1 ¤ until the start of your next turn.","fullText":"I HEREBY DECREE Whenever you play another\nPrincess character, all opposing characters get -1 ¤\nuntil the start of your next turn.","name":"I HEREBY DECREE","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2024-08-30","artists":["Vanessa Morales"],"artistsText":"Vanessa Morales","code":"fJ","color":"Amber","cost":4,"enchantedId":1162,"externalLinks":{"cardTraderId":294327,"cardTraderUrl":"https://www.cardtrader.com/cards/294327","cardmarketId":781342,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/Shimmering-Skies/Vanellope-von-Schweetz-Sugar-Rush-Princess-V1?language=1","tcgPlayerId":561473,"tcgPlayerUrl":"https://www.tcgplayer.com/product/561473"},"foilTypes":["None","Silver"],"fullIdentifier":"19/204 • EN • 5","fullName":"Vanellope von Schweetz - Sugar Rush Princess","fullText":"Shift 2 (You may pay 2 ⬡ to play this on top of one of\nyour characters named Vanellope von Schweetz.)\nI HEREBY DECREE Whenever you play another\nPrincess character, all opposing characters get -1 ¤\nuntil the start of your next turn.","fullTextSections":["Shift 2 (You may pay 2 ⬡ to play this on top of one of\nyour characters named Vanellope von Schweetz.)","I HEREBY DECREE Whenever you play another\nPrincess character, all opposing characters get -1 ¤\nuntil the start of your next turn."],"id":975,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set5/19_bf11bf51fd572fbaf876a3f6b619c8bac257b7c7.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set5/19_1051e2424833a2ce7b33b3441f67978911408290.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set5/19_0533c1e618f0fc4397acf5bdbddc41c61a61462d.jpg"},"inkwell":true,"keywordAbilities":["Shift"],"lore":2,"name":"Vanellope von Schweetz","number":19,"promoIds":[1195],"rarity":"Rare","simpleName":"vanellope von schweetz sugar rush princess","story":"Wreck-It Ralph","strength":2,"subtypes":["Floodborn","Hero","Princess","Racer"],"subtypesText":"Floodborn • Hero • Princess • Racer","type":"Character","version":"Sugar Rush Princess","willpower":4,"image":"https://api.lorcana.ravensburger.com/images/en/set5/19_1051e2424833a2ce7b33b3441f67978911408290.jpg"},
  "character_johnsmith_protector": {"abilities":[{"fullText":"Bodyguard (This character may enter play\nexerted. An opposing character who challenges\none of your characters must choose one with\nBodyguard if able.)","keyword":"Bodyguard","reminderText":"This character may enter play exerted. An opposing character who challenges one of your characters must choose one with Bodyguard if able.","type":"keyword"},{"effect":"Opponents must choose this character for actions and abilities if able.","fullText":"DO YOUR WORST Opponents must choose this\ncharacter for actions and abilities if able.","name":"DO YOUR WORST","type":"static"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2026-02-13","artists":["Grace Tran"],"artistsText":"Grace Tran","code":"GQ","color":"Steel","cost":5,"externalLinks":{},"foilTypes":["None","Silver"],"fullIdentifier":"193/204 • EN • 11","fullName":"John Smith - Undaunted Protector","fullText":"Bodyguard (This character may enter play\nexerted. An opposing character who challenges\none of your characters must choose one with\nBodyguard if able.)\nDO YOUR WORST Opponents must choose this\ncharacter for actions and abilities if able.","fullTextSections":["Bodyguard (This character may enter play\nexerted. An opposing character who challenges\none of your characters must choose one with\nBodyguard if able.)","DO YOUR WORST Opponents must choose this\ncharacter for actions and abilities if able."],"id":2656,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set11/193_280bf12e0d74c641acb6d53e4eb72a7d21b27fda.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set11/193_7d04154a2da78636cea0fd4bc178a92fa8c252ef.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set11/193_5167be20d0b6e931eb42b07f6cd7b06e52ffbd9e.jpg"},"inkwell":false,"keywordAbilities":["Bodyguard"],"lore":2,"name":"John Smith","number":193,"rarity":"Super Rare","simpleName":"john smith undaunted protector","story":"Pocahontas","strength":3,"subtypes":["Dreamborn","Hero"],"subtypesText":"Dreamborn • Hero","type":"Character","version":"Undaunted Protector","willpower":6,"image":"https://api.lorcana.ravensburger.com/images/en/set11/193_7d04154a2da78636cea0fd4bc178a92fa8c252ef.jpg"},
  "character_gadget_scientist": {"abilities":[{"effect":"When you play this character, if an opponent has more cards in their hand than you, you may draw a card.","fullText":"GOLLY! When you play this character, if an\nopponent has more cards in their hand than you,\nyou may draw a card.","name":"GOLLY!","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2025-06-20","artists":["Lisanne Koeteeuw"],"artistsText":"Lisanne Koeteeuw","code":"sr","color":"Emerald","cost":4,"externalLinks":{"cardTraderId":332939,"cardTraderUrl":"https://www.cardtrader.com/cards/332939","cardmarketId":826436,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/Reign-of-Jafar/Gadget-Hackwrench-Quirky-Scientist?language=1","tcgPlayerId":631412,"tcgPlayerUrl":"https://www.tcgplayer.com/product/631412"},"flavorText":"“The scarab's power source! I knew that if I dug\naround I'd find it!”","foilTypes":["None","Silver"],"fullIdentifier":"99/204 • EN • 8","fullName":"Gadget Hackwrench - Quirky Scientist","fullText":"GOLLY! When you play this character, if an\nopponent has more cards in their hand than you,\nyou may draw a card.","fullTextSections":["GOLLY! When you play this character, if an\nopponent has more cards in their hand than you,\nyou may draw a card."],"id":1763,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set8/99_916ce8f47944207945e36878ea77d7617ccf0d3d.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set8/99_22615c491d4ffed7f36ae0e9be8d00da6da0d593.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set8/99_c470fb2200d757bc8051e8e0d723b0732d0d06e9.jpg"},"inkwell":true,"lore":2,"name":"Gadget Hackwrench","number":99,"rarity":"Rare","simpleName":"gadget hackwrench quirky scientist","story":"Chip 'n Dale: Rescue Rangers","strength":3,"subtypes":["Storyborn","Ally","Inventor"],"subtypesText":"Storyborn • Ally • Inventor","type":"Character","version":"Quirky Scientist","willpower":2,"image":"https://api.lorcana.ravensburger.com/images/en/set8/99_22615c491d4ffed7f36ae0e9be8d00da6da0d593.jpg"},
  "character_stitch_rockstar": {"abilities":[{"fullText":"Shift 4 (You may pay 4 ⬡ to play this on top of one of\nyour characters named Stitch.)","keyword":"Shift","keywordValue":"4","keywordValueNumber":4,"reminderText":"You may pay 4 ⬡ to play this on top of one of your characters named Stitch.","type":"keyword"},{"effect":"Whenever you play a character with cost 2 or less, you may exert them to draw a card.","fullText":"ADORING FANS Whenever you play a character with\ncost 2 or less, you may exert them to draw a card.","name":"ADORING FANS","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2023-09-08","artists":["Simangaliso Sibaya"],"artistsText":"Simangaliso Sibaya","clarifications":["Q: Say I have Stitch - Rock Star in play and a cost 3 character in my hand. If I use Lantern so I can pay 1 ⬡ less to play that character, can I then exert them to draw a card?\nA: It's not the cost of the character you play that's reduced by Lantern; it's the amount you have to pay. The new character's cost would still be 3, so they wouldn't qualify to be a fan of Stitch."],"code":"0n","color":"Amber","cost":6,"externalLinks":{"cardTraderId":258931,"cardTraderUrl":"https://www.cardtrader.com/cards/258931","cardmarketId":727103,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/The-First-Chapter/Stitch-Rock-Star?language=1","tcgPlayerId":492708,"tcgPlayerUrl":"https://www.tcgplayer.com/product/492708"},"flavorText":"The best part about a beachside concert is that there's\nalways room for one more.","foilTypes":["None","Silver"],"fullIdentifier":"23/204 • EN • 1","fullName":"Stitch - Rock Star","fullText":"Shift 4 (You may pay 4 ⬡ to play this on top of one of\nyour characters named Stitch.)\nADORING FANS Whenever you play a character with\ncost 2 or less, you may exert them to draw a card.","fullTextSections":["Shift 4 (You may pay 4 ⬡ to play this on top of one of\nyour characters named Stitch.)","ADORING FANS Whenever you play a character with\ncost 2 or less, you may exert them to draw a card."],"id":23,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set1/23_61d1aa1725f7ce9ecc72413a112a1df086adf0fc.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set1/23_a962999a02d161d6f5341c69469c12bf30e0bd2b.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set1/23_c8fb8b53b480d3cb4239a555d2f40154bb8c4e52.jpg"},"inkwell":true,"keywordAbilities":["Shift"],"lore":3,"name":"Stitch","number":23,"promoIds":[660,688],"rarity":"Super Rare","reprintedAsIds":[1939],"simpleName":"stitch rock star","story":"Lilo & Stitch","strength":3,"subtypes":["Floodborn","Hero","Alien"],"subtypesText":"Floodborn • Hero • Alien","type":"Character","version":"Rock Star","willpower":5,"image":"https://api.lorcana.ravensburger.com/images/en/set1/23_a962999a02d161d6f5341c69469c12bf30e0bd2b.jpg"},
  "character_mickey_pilot": {"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2023-09-08","artists":["Juan Diego Leon"],"artistsNormalized":["Juan Diego León"],"artistsText":"Juan Diego Leon","code":"1r","color":"Emerald","cost":3,"externalLinks":{"cardTraderId":259057,"cardTraderUrl":"https://www.cardtrader.com/cards/259057","cardmarketId":729270,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/The-First-Chapter/Mickey-Mouse-Steamboat-Pilot?language=1","tcgPlayerId":492709,"tcgPlayerUrl":"https://www.tcgplayer.com/product/492709"},"flavorText":"On rivers throughout the Inklands, the little\nsteamboat's whistle answers the cheery tunes of\nits pilot.","foilTypes":["None","Silver"],"fullIdentifier":"89/204 • EN • 1","fullName":"Mickey Mouse - Steamboat Pilot","fullText":"","fullTextSections":[],"id":89,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set1/89_aef26081ed16140658856f9e4d11085f517b0119.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set1/89_a324b64e969a865208b357c12cde2f2ae8ff9190.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set1/89_a229a2dfe6be9d6a1454a102e6b5454aa1fc3c86.jpg"},"inkwell":true,"lore":1,"name":"Mickey Mouse","number":89,"rarity":"Common","reprintedAsIds":[2016],"simpleName":"mickey mouse steamboat pilot","story":"Mickey Mouse & Friends","strength":3,"subtypes":["Storyborn","Hero","Captain"],"subtypesText":"Storyborn • Hero • Captain","type":"Character","version":"Steamboat Pilot","willpower":4,"image":"https://api.lorcana.ravensburger.com/images/en/set1/89_a324b64e969a865208b357c12cde2f2ae8ff9190.jpg"},
  "character_jasmine_strategist": {"abilities":[{"fullText":"Shift 2 (You may pay 2 ⬡ to play this on top of one of\nyour characters named Jasmine.)","keyword":"Shift","keywordValue":"2","keywordValueNumber":2,"reminderText":"You may pay 2 ⬡ to play this on top of one of your characters named Jasmine.","type":"keyword"},{"effect":"Whenever this character quests, look at the top 3 cards of your deck. You may reveal an Ally character card and put it into your hand. Put the rest on the bottom of your deck in any order.","fullText":"ALWAYS PLANNING Whenever this character quests,\nlook at the top 3 cards of your deck. You may reveal\nan Ally character card and put it into your hand. Put\nthe rest on the bottom of your deck in any order.","name":"ALWAYS PLANNING","type":"triggered"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2025-06-20","artists":["Hedvig H-S"],"artistsText":"Hedvig H-S","code":"tB","color":"Sapphire-Steel","colors":["Sapphire","Steel"],"cost":4,"enchantedId":1885,"externalLinks":{"cardTraderId":331989,"cardTraderUrl":"https://www.cardtrader.com/cards/331989","cardmarketId":826509,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/Reign-of-Jafar/Jasmine-Steady-Strategist-V1?language=1","tcgPlayerId":631467,"tcgPlayerUrl":"https://www.tcgplayer.com/product/631467"},"foilTypes":["None","Silver"],"fullIdentifier":"171/204 • EN • 8","fullName":"Jasmine - Steady Strategist","fullText":"Shift 2 (You may pay 2 ⬡ to play this on top of one of\nyour characters named Jasmine.)\nALWAYS PLANNING Whenever this character quests,\nlook at the top 3 cards of your deck. You may reveal\nan Ally character card and put it into your hand. Put\nthe rest on the bottom of your deck in any order.","fullTextSections":["Shift 2 (You may pay 2 ⬡ to play this on top of one of\nyour characters named Jasmine.)","ALWAYS PLANNING Whenever this character quests,\nlook at the top 3 cards of your deck. You may reveal\nan Ally character card and put it into your hand. Put\nthe rest on the bottom of your deck in any order."],"id":1835,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set8/171_8ef5f59458ae1818f0f1efeb9f700b996511dcac.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set8/171_d709513c423116e2ef43fe17fce315a3f8452ee6.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set8/171_e78cf568f13e34f652bd068e7e4e412fc407b887.jpg"},"inkwell":true,"keywordAbilities":["Shift"],"lore":1,"name":"Jasmine","number":171,"rarity":"Super Rare","simpleName":"jasmine steady strategist","story":"Aladdin","strength":2,"subtypes":["Floodborn","Hero","Princess"],"subtypesText":"Floodborn • Hero • Princess","type":"Character","version":"Steady Strategist","willpower":5,"image":"https://api.lorcana.ravensburger.com/images/en/set8/171_d709513c423116e2ef43fe17fce315a3f8452ee6.jpg"},
  "item_lantern": {"abilities":[{"costs":["⟳"],"costsText":"⟳","effect":"You pay 1 ⬡ less for the next character you play this turn.","fullText":"BIRTHDAY LIGHTS ⟳ — You pay 1 ⬡ less for the next\ncharacter you play this turn.","name":"BIRTHDAY LIGHTS","type":"activated"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2023-09-08","artists":["Eri Welli"],"artistsText":"Eri Welli","clarifications":["Q: Say I have Stitch - Rock Star in play and a cost 3 character in my hand. If I use Lantern so I can pay 1 ⬡ less to play that character, can I then exert them to draw a card?\nA: It's not the cost of the character you play that's reduced by Lantern; it's the amount you have to pay. The new character's cost would still be 3, so they wouldn't qualify to be a fan of Stitch."],"code":"0x","color":"Amber","cost":2,"externalLinks":{"cardTraderId":258959,"cardTraderUrl":"https://www.cardtrader.com/cards/258959","cardmarketId":727113,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/The-First-Chapter/Lantern?language=1","tcgPlayerId":493500,"tcgPlayerUrl":"https://www.tcgplayer.com/product/493500"},"flavorText":"Lanterns fill the sky on one special night, beacons of\nhope and love.","foilTypes":["None","Silver"],"fullIdentifier":"33/204 • EN • 1","fullName":"Lantern","fullText":"BIRTHDAY LIGHTS ⟳ — You pay 1 ⬡ less for the next\ncharacter you play this turn.","fullTextSections":["BIRTHDAY LIGHTS ⟳ — You pay 1 ⬡ less for the next\ncharacter you play this turn."],"id":33,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set1/33_699230649186efe5a7276536ba65166cca070205.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set1/33_0387aaa8150e80c49743e0a7fd898eb3f4ea2816.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set1/33_3a7342f6a4e7cb4e8f8b013d3ca56d5705e677ab.jpg"},"inkwell":false,"name":"Lantern","number":33,"rarity":"Rare","reprintedAsIds":[1968],"simpleName":"lantern","story":"Tangled","type":"Item","image":"https://api.lorcana.ravensburger.com/images/en/set1/33_0387aaa8150e80c49743e0a7fd898eb3f4ea2816.jpg"},
  "location_abandoned_lab": {"abilities":[{"effect":"Characters gain “⟳ — Draw a card” while here.","fullText":"STARTLING DISCOVERY Characters gain “⟳ — Draw a card” while here.","name":"STARTLING DISCOVERY","type":"static"}],"allowedInFormats":{"Core":{"allowed":true},"Infinity":{"allowed":true}},"allowedInTournamentsFromDate":"2025-11-07","artists":["Priya Kakati"],"artistsText":"Priya Kakati","code":"Ap","color":"Amethyst","cost":2,"externalLinks":{"cardTraderId":356504,"cardTraderUrl":"https://www.cardtrader.com/cards/356504","cardmarketId":856059,"cardmarketUrl":"https://www.cardmarket.com/en/Lorcana/Products/Singles/Whispers-in-the-Well/The-Great-Illuminary-Abandoned-Laboratory?language=1","tcgPlayerId":658467,"tcgPlayerUrl":"https://www.tcgplayer.com/product/658467"},"flavorText":"“Remember, we're looking for clues to who tore up the lorebook pages.”\n—Elisa Maza","foilTypes":["None","Silver"],"fullIdentifier":"68/204 • EN • 10","fullName":"The Great Illuminary - Abandoned Laboratory","fullText":"STARTLING DISCOVERY Characters gain “⟳ — Draw a card” while here.","fullTextSections":["STARTLING DISCOVERY Characters gain “⟳ — Draw a card” while here."],"id":2257,"images":{"foilMask":"https://api.lorcana.ravensburger.com/images/en/set10/68_c0bf600c3ac94bdc5b92bf02b84d0b97c04c5f27.jpg","full":"https://api.lorcana.ravensburger.com/images/en/set10/68_a50f12321fcf05a2d15ea5f8e37e8715083a3d65.jpg","thumbnail":"https://api.lorcana.ravensburger.com/images/en/set10/68_05572bd7bad6ec1881a725584ded74f4da8f9f90.jpg"},"inkwell":true,"lore":1,"moveCost":1,"name":"The Great Illuminary","number":68,"promoIds":[2440],"rarity":"Uncommon","simpleName":"the great illuminary abandoned laboratory","story":"Lorcana","type":"Location","version":"Abandoned Laboratory","willpower":3,"image":"https://api.lorcana.ravensburger.com/images/en/set10/68_a50f12321fcf05a2d15ea5f8e37e8715083a3d65.jpg"},
  "character_jackjack_potential": {"fullName":"Jack-Jack Parr - Incredible Potential","name":"Jack-Jack Parr","version":"Incredible Potential","type":"Character","color":"Ruby","cost":4,"inkwell":true,"strength":4,"willpower":4,"lore":1,"subtypesText":"Storyborn • Super • Hero","fullText":"WEIRD THINGS ARE HAPPENING At the start of your turn,\nyou may put the top card of your deck into your discard.\nIf its card type is:\n• character, this character gets +2 ¤ this turn.\n• action or item, this character gets +2 ◊ this turn.\n• location, banish chosen character.","rarity":"Super Rare","set":"12","number":121,"image":"https://api.lorcana.ravensburger.com/images/en/set12/121_5be0c6e34af28b7ae21b074c7a7efb5ba210c5b5.jpg"},
  "character_jasmine_resourceful": {"fullName":"Jasmine - Resourceful Infiltrator","name":"Jasmine","version":"Resourceful Infiltrator","type":"Character","cost":1,"inkwell":true,"strength":1,"willpower":2,"lore":1,"set":"8","number":162,"image":"https://api.lorcana.ravensburger.com/images/en/set8/162_eeb1a4ef233fc727285d6901965a9eba4571fc27.jpg"},
  "character_mulan_diplomat": {"fullName":"Mulan - Considerate Diplomat","name":"Mulan","version":"Considerate Diplomat","type":"Character","cost":5,"inkwell":true,"strength":3,"willpower":5,"lore":2,"set":"9","number":142,"image":"https://api.lorcana.ravensburger.com/images/en/set9/142_7a23d28ca4130be640d497658c73253c8946a3ed.jpg"},
  "character_stitch_trickster": {"fullName":"Stitch - Little Trickster","name":"Stitch","version":"Little Trickster","type":"Character","cost":2,"inkwell":true,"strength":1,"willpower":3,"lore":1,"set":"6","number":26,"image":"https://api.lorcana.ravensburger.com/images/en/set6/26_4b66573bcfc20857e4be463b7179e9febca4deca.jpg"},
  "character_rex_dinosaur": {"fullName":"Rex - Protective Dinosaur","name":"Rex","version":"Protective Dinosaur","type":"Character","cost":2,"inkwell":true,"strength":3,"willpower":1,"lore":1,"set":"12","number":10,"image":"https://api.lorcana.ravensburger.com/images/en/set12/10_8634abb5eb7d8323a0f335589a17387414f3456d.jpg"},
  "character_vanellope_champ": {"fullName":"Vanellope von Schweetz - Sugar Rush Champ","name":"Vanellope von Schweetz","version":"Sugar Rush Champ","type":"Character","cost":1,"inkwell":true,"strength":2,"willpower":2,"lore":1,"set":"5","number":6,"image":"https://api.lorcana.ravensburger.com/images/en/set5/6_d3adda047c4d76aae9f126f995286c67e2ffda03.jpg"},
  "action_three_arrows": {"fullName":"Three Arrows","name":"Three Arrows","type":"Action","cost":3,"inkwell":true,"set":"12","number":197,"image":"https://api.lorcana.ravensburger.com/images/en/set12/197_354cb93926a7d55d8a375023f579fe21b5a5464d.jpg"},
  "action_develop_your_brain": {"fullName":"Develop Your Brain","name":"Develop Your Brain","type":"Action","cost":1,"inkwell":true,"fullText":"Look at the top 2 cards of your deck. Put one into your\nhand and the other on the bottom of the deck.","set":"1","number":161,"image":"https://api.lorcana.ravensburger.com/images/en/set1/161_45a513aee64ff3e38f0dd116a15d21fc6d3a4dc7.jpg"},
  "character_scar_king": {"fullName":"Scar - Finally King","name":"Scar","version":"Finally King","type":"Character","cost":5,"inkwell":false,"strength":5,"willpower":4,"lore":2,"set":"9","number":175,"image":"https://api.lorcana.ravensburger.com/images/en/set9/175_a36e50ae37db0f816406604eefe69b2eb596660c.jpg"},
  "character_mickey_true_friend": {"fullName":"Mickey Mouse - True Friend","name":"Mickey Mouse","version":"True Friend","type":"Character","color":"Amber","cost":3,"inkwell":true,"strength":3,"willpower":3,"lore":2,"subtypesText":"Storyborn • Hero","flavorText":"As long as he's around, newcomers to the Great Illuminary will always get a warm welcome.","set":"1","number":12,"image":"https://api.lorcana.ravensburger.com/images/en/set1/12_da68c89ea3fc28a3a7396c30ab3da45e0f204eea.jpg"}
};
